### ISSUE TITLE
embedded-msgpack drags in std; cannot build with no_std

### ISSUE THREAD

**Issue by theunkn0wn1** [Sympatron/embedded-msgpack#1]
I am evaluating this crate for use in an embedded environment.
Unfortunately, it seems to be dragging in the `std` crate when the `serde` feature is enabled, which is a showstopper when embedded applications don't get the `std` crate.
```
error[E0463]: can't find crate for `std`
  --> /home/orion/.cargo/registry/src/github.com-1ecc6299db9ec823/embedded-msgpack-0.2.1/src/decode/serde/mod.rs:19:5
   |
19 |     extern crate std;
   |     ^^^^^^^^^^^^^^^^^ can't find crate
   |
   = note: the `thumbv7em-none-eabihf` target may not support the standard library
```

Further, it cannot be compiled without the `serde` feature, since it wouldn't get linked to `serde_bytes`, which is linked to unconditionally. 
```
error[E0432]: unresolved import `serde_bytes`
  --> /home/orion/.cargo/registry/src/github.com-1ecc6299db9ec823/embedded-msgpack-0.2.1/src/lib.rs:17:9
   |
17 | pub use serde_bytes::Bytes;
   |         ^^^^^^^^^^^ use of undeclared crate or module `serde_bytes`

```

**Comment by Sympatron** [comment]
Thank you for your interest!

> Unfortunately, it seems to be dragging in the std crate when the serde feature is enabled

This was not intended and only happened for debug builds. This is now fixed in 0.2.2.

> Further, it cannot be compiled without the serde feature

In 0.2.2 the `serde_bytes` export is now conditional.

Please report any further issues you have with `embedded-msgpack`!
