### ISSUE TITLE
Decoding messagepack timestamps

### ISSUE THREAD

**Issue by jsoverson** [Sympatron/embedded-msgpack#4]
Is there an example for decoding messagepack timestamps? It seems like it's implemented but I can't find out how to make it work. decoding/encoding the `Timestamp` struct encodes it as a map and embedded-msppack doesn't seem to decode timestamps encoded in the messagepack extension format.

**Comment by Sympatron** [comment]
`embedded-msgpack` does currently not support de-/serialization of `Timestamp`s with `serde`.

You can serialize them manually like this:
```rust
let mut buffer = [0u8; 15];
let t = embedded_msgpack::timestamp::Timestamp::new(42, 0).unwrap();
t.write_into_slice(&mut buffer).ok();
```

Deserialization is not implemented. PRs are welcome. :)

**Comment by Sympatron** [comment]
Please check out version `0.3.0`.
Serialization and deserialization of `Timestamp` is now possible using `serde`.
